spring.application.name=systeme-paiement-decentralise

# --- CONFIGURATION DE LA BASE DE DONNÉES ---
# Spring Boot sait interpréter DATABASE_URL s'il est au bon format
spring.datasource.url=jdbc:${DATABASE_URL:h2:mem:testdb}
spring.datasource.username=${POSTGRES_USER:sa}
spring.datasource.password=${POSTGRES_PASSWORD:}

# Dialecte pour PostgreSQL (Railway) ou H2 (Local)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# --- JWT & SÉCURITÉ ---
jwt.secret=${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
jwt.expiration=86400000